### ISSUE TITLE
When will the complete code be released?

### ISSUE THREAD

**Issue by ghost** [boheumd/A2Summ#1]
Hi!

thanks for your contribution for open source. I just read A2Summ and very interested in your model, Saddly, I found the repo only contains README, and my question is when will complete code of A2Summ be committed?

Best wishes!

**Comment by boheumd** [comment]
Thank you for your interest in our work. We are planning to release the code in the next two to three weeks.

**Comment by ghost** [comment]
> Thank you for your interest in our work. We are planning to release the code in the next two to three weeks.

Thanks!
