### ISSUE TITLE
python train.py --dataset ${dataset}

### ISSUE THREAD

**Issue by Pwoer-zy** [boheumd/A2Summ#10]
Hi Bo,
when I choose a CNN data set training model, it is impossible to generate the model_best_video.pt, and only the model_best_text.pt. However, when using the Daliy_mail dataset training model, the model_best_text.pt and model_best_video.pt can be generated. I checked that the code did not find the reason. Do you know what the reason is? 
Looking forward to your reply, thank you very much, I wish you all the best!

**Comment by boheumd** [comment]
Hello, the CNN dataset does not have the ground-truth video summary while the Daily_Mail has the ground-truth video and text summary. So we can only evaluate the text summary results and get the model_best_text.pt on the CNN dataset.

**Comment by Pwoer-zy** [comment]
Hello，how do you get the model_best_video.pt of the CNN dataset in the saved_model you provided? Looking forward to your reply! Thank you so much.

**Comment by Pwoer-zy** [comment]
> 

Hello，how do you get the model_best_video.pt of the CNN dataset in the saved_model you provided? Looking forward to your reply! Thank you so much.

**Comment by boheumd** [comment]
Hello, the model_best_video.pt only evaluates the val_cos which is always 0 for the CNN dataset as you can see from https://github.com/boheumd/A2Summ/blob/main/train_msmo.py#L71. You can ignore the model_best_video.pt in the saved_model link. Sorry for the confusion.
