### ISSUE TITLE
Question about logs

### ISSUE THREAD

**Issue by ghost** [boheumd/A2Summ#6]
Thanks for your contribution for open source! 
I just reviewed logs using tensorboard. It seems that before using SummaryWriter.add_scalar, may be you need to add some prefix like split_{index}  for datasets like SumMe. 
![image](https://user-images.githubusercontent.com/46026431/233906322-e06b3f11-f8c5-4759-82bf-811001c34d9b.png)

image above generated from training A2summ using SumMe dataset.

**Comment by boheumd** [comment]
Thank you for your suggestion. We have updated the code as you suggested.
