### ISSUE TITLE
How to calculate rho and tau in SumMe and TVSum

### ISSUE THREAD

**Issue by itruonghai** [boheumd/A2Summ#9]
I saw in the paper that you reported both F1, rho and tau. However, when I tried to reproduce the results, I can not find any function that calculate rho and tau result. How could I produce the value of rho and tau?

**Comment by boheumd** [comment]
Hello. Thank you for your interest in our work. You can refer to the following code to calculate rho and tau results.
https://github.com/e-apostolidis/CA-SUM/blob/main/evaluation/choose_best_model.py#L67
https://gitlab.uni-hannover.de/hussainkanafani/unsupervised-video-summarization/-/blob/master/src/evaluation/BaseEvaluator.py#L7
https://github.com/TIBHannover/MSVA/blob/master/train.py#L430
